# Generated by Django 5.2.7 on 2025-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutuspage_contactuspage_faqpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaqPage',
        ),
        migrations.AlterModelOptions(
            name='contactuspage',
            options={'verbose_name': 'صفحه ارتباط با ما', 'verbose_name_plural': 'صفحه ارتباط با ما'},
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='content',
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='address',
            field=models.CharField(default=1, max_length=300, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='email',
            field=models.EmailField(default='s', max_length=200, verbose_name='ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='facebook_link',
            field=models.CharField(default='s', max_length=200, verbose_name='لینک فیسبوک'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='instagram_link',
            field=models.CharField(default='s', max_length=200, verbose_name='لینک اینستاگرام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='linkedin_link',
            field=models.CharField(default='w', max_length=200, verbose_name='لینک لینکدین'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='owner_name',
            field=models.CharField(default='fahimreza', max_length=200, verbose_name='نام مدیریت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='phone_number',
            field=models.CharField(default='iss', max_length=11, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='twitter_link',
            field=models.CharField(default='sd', max_length=200, verbose_name='لینک توییتر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='working_hours',
            field=models.CharField(default='a', max_length=200, verbose_name='ساعات کاری'),
            preserve_default=False,
        ),
    ]
