# Generated by Django 5.2.7 on 2025-11-20 03:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_faqpage_alter_contactuspage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='محتوا'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='content_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='محتوا'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='address_en',
            field=models.CharField(max_length=300, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='address_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='owner_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='نام مدیریت'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='owner_name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='نام مدیریت'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
    ]
