# Generated by Django 5.2.7 on 2025-11-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'نمایش'), (2, 'عدم نمایش')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'ویژه'), (2, 'عادی')], default=1, verbose_name='نوع'),
        ),
    ]
