# Generated by Django 5.2.7 on 2025-11-20 03:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_status_alter_blogmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='جزئیات'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='جزئیات'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
    ]
