# Generated by Django 5.2.7 on 2025-11-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogmodel_description_en_blogmodel_description_fa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategorymodel',
            options={'verbose_name': 'دسته بندی بلاگ', 'verbose_name_plural': 'دسته بندی های بلاگ'},
        ),
        migrations.CreateModel(
            name='BlogImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='تصویر')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel', verbose_name='بلاگ')),
            ],
            options={
                'verbose_name': 'تصویر بلاگ',
                'verbose_name_plural': 'تصاویر بلاگ',
            },
        ),
    ]
