# Generated by Django 5.2.7 on 2025-11-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcategorymodel_options_blogimagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategorymodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogcategorymodel',
            name='updated_at',
        ),
    ]
