# Generated by Django 5.2.7 on 2025-11-20 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogcategorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.ForeignKey(default='s', on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategorymodel', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
