# Generated by Django 5.2.7 on 2025-11-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorymodel',
            name='name',
            field=models.CharField(default='test', max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
