# Generated by Django 5.2.7 on 2025-11-20 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcategorymodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
