# Generated by Django 5.2.7 on 2025-11-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogcategorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorymodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
    ]
