# Generated by Django 5.2.7 on 2025-11-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogcategorymodel_name_en_blogcategorymodel_name_fa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategorymodel',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='blogcategorymodel',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='blogcategorymodel',
            old_name='name_fa',
            new_name='title_fa',
        ),
    ]
